# Generated by Django 5.0.1 on 2024-10-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36, unique=True)),
                ('plan', models.CharField(choices=[('inout_base', 'INOUT Проект База'), ('inout_business', 'INOUT Проект Бизнес'), ('inout_platform', 'INOUT Проект Платформа')], max_length=20)),
                ('user_amount', models.PositiveIntegerField(default=5)),
                ('help_desk', models.BooleanField(default=False)),
                ('dms', models.BooleanField(default=False)),
                ('risk_management', models.BooleanField(default=False)),
                ('custom_branding', models.BooleanField(default=False)),
                ('gitlab_integration', models.BooleanField(default=False)),
                ('b2b_crm', models.BooleanField(default=False)),
                ('knowledge_base', models.BooleanField(default=False)),
                ('asset_management', models.BooleanField(default=False)),
                ('private_cloud', models.BooleanField(default=False)),
                ('billing', models.CharField(choices=[('in_month', 'Ежемесячно'), ('in_year', 'Ежегодно')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('legal_address', models.TextField(blank=True)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Банковская карта'), ('pay_check', 'Счет на оплату')], default='credit_card', max_length=20)),
            ],
        ),
    ]
