# Generated by Django 5.0.1 on 2024-10-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='session_id',
            field=models.CharField(default='default', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_id',
            field=models.CharField(default='default', max_length=36),
            preserve_default=False,
        ),
    ]
