# Generated by Django 5.0.1 on 2024-10-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_gateway', '0003_rename_price_addon_price_per_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='price_per_user',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='price_per_user',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='description',
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
    ]
