version: '3.3'
services:
  db:
    tty: True
    stdin_open: true
    image: postgres:14
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    tty: True
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8052 --timeout 1200
    volumes:
      - .:/code
    ports:
      - '8052:8052'
    env_file:
      - ./.env
    depends_on:
      - db

#  nginx:
#    build: ./.deploy/nginx
#    volumes:
#      - .:/code
#    ports:
#      - '8152:80'
#    depends_on:
#      - app

volumes:
  db:
    driver: local
  api:
    driver: local
