# Generated by Django 5.0.1 on 2024-04-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStudyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Учебный центр (Категории)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='studypage',
            options={'verbose_name': 'Учебный центр'},
        ),
    ]
