# Generated by Django 5.0.1 on 2024-04-11 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_categorystudypage_alter_studypage_options'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('label', models.CharField(max_length=64, verbose_name='Лейбл')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Учебный центр (Контент)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
