# Generated by Django 5.0.1 on 2024-04-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_studycontentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystudypage',
            name='show_breadcrumbs',
            field=models.BooleanField(default=True, verbose_name='Отображать хлебные крошки'),
        ),
        migrations.AddField(
            model_name='studypage',
            name='show_breadcrumbs',
            field=models.BooleanField(default=True, verbose_name='Отображать хлебные крошки'),
        ),
    ]
