# Generated by Django 5.0.1 on 2024-05-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_categorystudypage_show_breadcrumbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studypage',
            name='show_main_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в главном меню'),
        ),
    ]
