# Generated by Django 5.0.1 on 2024-10-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginPage',
        ),
    ]
