# Generated by Django 5.0.1 on 2024-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docspage',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
