# Generated by Django 5.0.1 on 2024-02-13 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articlepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
