# Generated by Django 5.0.1 on 2024-03-14 18:28

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlepage_publish_date'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='content',
            field=wagtail.fields.RichTextField(default='', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro',
            field=models.CharField(max_length=255, verbose_name='Интро'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
