# Generated by Django 5.0.1 on 2024-04-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articlepage_content_alter_articlepage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
