# Generated by Django 5.0.1 on 2024-04-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcategorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='reading_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время чтения'),
        ),
    ]
