# Generated by Django 5.0.1 on 2024-04-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articlepage_reading_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='publish_date',
        ),
    ]
