# Generated by Django 5.0.1 on 2024-03-18 08:02

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_page_block'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.CharField(max_length=512, verbose_name='Описание раздела')),
                ('page_block', wagtail.fields.StreamField([('big_card', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', label='Основной заголовок')), ('title_left', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок слева')), ('text_left', wagtail.blocks.CharBlock(form_classname='title', label='Текст слева')), ('link_left', wagtail.blocks.CharBlock(form_classname='title', label='Ссылка слева')), ('title_right', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок справа')), ('text_right', wagtail.blocks.CharBlock(form_classname='title', label='Текст справа')), ('link_right', wagtail.blocks.CharBlock(form_classname='title', label='Ссылка справа'))]))], blank=True, verbose_name='Блоки на странице')),
            ],
            options={
                'verbose_name': 'Страница ресурсов',
            },
            bases=('wagtailcore.page',),
        ),
    ]
