# Generated by Django 5.0.1 on 2024-04-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespage',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
