# Generated by Django 5.0.1 on 2024-04-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_partnerpage_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepage',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
