# Generated by Django 5.0.1 on 2024-04-03 07:13

import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_becomepartnerpage_ordering_faqpage_ordering_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMenuLeftPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка')),
                ('page_block', wagtail.fields.StreamField([('blog_slider_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок')), ('link', wagtail.blocks.CharBlock(form_classname='link', label='Ссылка подробнее')), ('count_articles', wagtail.blocks.IntegerBlock(label='Количество записей в слайдере'))])), ('feature_horizontal_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок')), ('sub_blocks', wagtail.blocks.StreamBlock([('sub_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок')), ('text', wagtail.blocks.CharBlock(label='Текст')), ('icon', wagtail.blocks.ChoiceBlock(choices=[('star', 'Звездочка'), ('star', 'Дашборд'), ('star', 'Шестеренка')], label='Иконка'))]))], label='Блоки'))])), ('clients_logo_block', wagtail.blocks.StructBlock([('client_logo', wagtail.blocks.StreamBlock([('sub_block', wagtail.blocks.StructBlock([('logo_light', wagtail.documents.blocks.DocumentChooserBlock(label='Логотип для светлой темы')), ('logo_dark', wagtail.documents.blocks.DocumentChooserBlock(label='Логотип для темной темы'))]))], label='Лого'))])), ('feature_tab_left_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок')), ('tabs', wagtail.blocks.StreamBlock([('sub_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок')), ('text', wagtail.blocks.CharBlock(form_classname='title', label='Текст')), ('link', wagtail.blocks.CharBlock(form_classname='link', label='Ссылка попробовать')), ('logo', wagtail.images.blocks.ImageChooserBlock(label='Картинка'))]))], label='Табы'))])), ('project_block', wagtail.blocks.StructBlock([('head_title', wagtail.blocks.CharBlock(form_classname='title', label='Название проекта')), ('title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок')), ('description', wagtail.blocks.CharBlock(form_classname='title', label='Описание')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Картинка')), ('feature_blocks', wagtail.blocks.StreamBlock([('feature_blocks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок')), ('description', wagtail.blocks.CharBlock(form_classname='description', label='Описание')), ('link', wagtail.blocks.CharBlock(form_classname='link', label='Ссылка подробнее'))]))], label='Блог с фичей'))])), ('hero_products', wagtail.blocks.StructBlock([('sub_title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок проекта')), ('title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок')), ('text', wagtail.blocks.CharBlock(form_classname='title', label='Текст')), ('logo_dark', wagtail.images.blocks.ImageChooserBlock(label='Картинка для темного фона')), ('logo_light', wagtail.images.blocks.ImageChooserBlock(label='Картинка для светлого фона'))])), ('big_card', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', label='Основной заголовок')), ('title_left', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок слева')), ('text_left', wagtail.blocks.CharBlock(form_classname='title', label='Текст слева')), ('link_left', wagtail.blocks.CharBlock(form_classname='title', label='Ссылка слева')), ('title_right', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок справа')), ('text_right', wagtail.blocks.CharBlock(form_classname='title', label='Текст справа')), ('link_right', wagtail.blocks.CharBlock(form_classname='title', label='Ссылка справа'))])), ('hero_feature_products', wagtail.blocks.StructBlock([('sub_title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок проекта')), ('title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок')), ('text', wagtail.blocks.CharBlock(form_classname='title', label='Текст')), ('link', wagtail.blocks.CharBlock(form_classname='title', label='Ссылка'))]))], blank=True, verbose_name='Блоки на странице')),
            ],
            options={
                'verbose_name': 'Шаблон с меню слева',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главный шаблон'},
        ),
    ]
