# Generated by Django 5.0.1 on 2024-04-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_homemenuleftpage_page_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='review',
            field=models.CharField(max_length=512, verbose_name='Отзыв'),
        ),
    ]
