# Generated by Django 5.0.1 on 2024-04-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemenuleftpage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
