# Generated by Django 5.0.1 on 2024-04-11 14:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homemenuleftpage_image_homepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=wagtail.fields.RichTextField(verbose_name='Ответ'),
        ),
    ]
