# Generated by Django 5.0.1 on 2024-04-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_homemenuleftpage_show_left_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_left_menu',
            field=models.BooleanField(default=False, verbose_name='Отображать левое меню с потомками'),
        ),
    ]
