# Generated by Django 5.0.1 on 2024-04-21 19:09

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_homemenuleftpage_show_breadcrumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribepage',
            name='page_block',
            field=wagtail.fields.StreamField([('blog_slider_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', label='Заголовок')), ('link', wagtail.blocks.CharBlock(form_classname='link', label='Ссылка подробнее')), ('count_articles', wagtail.blocks.IntegerBlock(label='Количество записей в слайдере'))]))], blank=True, verbose_name='Блоки на странице'),
        ),
    ]
