# Generated by Django 5.0.1 on 2024-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_subscribepage_page_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemenuleftpage',
            name='color',
            field=models.CharField(choices=[('colors-dark-gradient-base-up', 'colors-dark-gradient-base-up'), ('colors-dark-gradient-platform-up', 'colors-dark-gradient-platform-up'), ('colors-dark-gradient-integration-up', 'colors-dark-gradient-integration-up'), ('colors-dark-gradient-deployment-up', 'colors-dark-gradient-deployment-up'), ('colors-dark-gradient-business-up', 'colors-dark-gradient-business-up')], default='colors-dark-gradient-base-up'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='color',
            field=models.CharField(choices=[('colors-dark-gradient-base-up', 'colors-dark-gradient-base-up'), ('colors-dark-gradient-platform-up', 'colors-dark-gradient-platform-up'), ('colors-dark-gradient-integration-up', 'colors-dark-gradient-integration-up'), ('colors-dark-gradient-deployment-up', 'colors-dark-gradient-deployment-up'), ('colors-dark-gradient-business-up', 'colors-dark-gradient-business-up')], default='colors-dark-gradient-base-up'),
        ),
    ]
