# Generated by Django 5.0.1 on 2024-05-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_homemenuleftpage_show_main_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomepartnerpage',
            name='show_main_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в главном меню'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='show_main_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в главном меню'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='show_main_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в главном меню'),
        ),
        migrations.AddField(
            model_name='pricepage',
            name='show_main_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в главном меню'),
        ),
        migrations.AddField(
            model_name='resourcespage',
            name='show_main_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в главном меню'),
        ),
        migrations.AddField(
            model_name='reviewpage',
            name='show_main_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в главном меню'),
        ),
        migrations.AddField(
            model_name='subscribepage',
            name='show_main_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в главном меню'),
        ),
    ]
