# Generated by Django 5.0.1 on 2024-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_emptypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emptypage',
            name='show_main_menu',
            field=models.BooleanField(default=True, verbose_name='Отображать в главном меню'),
        ),
    ]
